// -*- C++ -*-
#ifndef triboson_v1_H
#define triboson_v1_H
#include "Math/LorentzVector.h"
#include "Math/Point3D.h"
#include "TMath.h"
#include "TBranch.h"
#include "TTree.h"
#include "TH1F.h"
#include "TFile.h"
#include "TBits.h"
#include <vector> 
#include <unistd.h> 
typedef ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > LorentzVector;

// Generated with the command
// makeCMS3ClassFiles("chain files", "t", "triboson_v1", "triboson_v1_np", "cms3")

using namespace std; 
class triboson_v1 {
private: 
protected: 
	unsigned int index;
	int	run_;
	TBranch *run_branch;
	bool run_isLoaded;
	int	lumi_;
	TBranch *lumi_branch;
	bool lumi_isLoaded;
	unsigned long long	evt_;
	TBranch *evt_branch;
	bool evt_isLoaded;
	int	isData_;
	TBranch *isData_branch;
	bool isData_isLoaded;
	bool	evt_passgoodrunlist_;
	TBranch *evt_passgoodrunlist_branch;
	bool evt_passgoodrunlist_isLoaded;
	float	evt_scale1fb_;
	TBranch *evt_scale1fb_branch;
	bool evt_scale1fb_isLoaded;
	float	evt_xsec_;
	TBranch *evt_xsec_branch;
	bool evt_xsec_isLoaded;
	float	evt_kfactor_;
	TBranch *evt_kfactor_branch;
	bool evt_kfactor_isLoaded;
	float	evt_filter_;
	TBranch *evt_filter_branch;
	bool evt_filter_isLoaded;
	int	evt_nEvts_;
	TBranch *evt_nEvts_branch;
	bool evt_nEvts_isLoaded;
	vector<TString> *evt_dataset_;
	TBranch *evt_dataset_branch;
	bool evt_dataset_isLoaded;
	float	puWeight_;
	TBranch *puWeight_branch;
	bool puWeight_isLoaded;
	int	nVert_;
	TBranch *nVert_branch;
	bool nVert_isLoaded;
	int	nTrueInt_;
	TBranch *nTrueInt_branch;
	bool nTrueInt_isLoaded;
	float	rho_;
	TBranch *rho_branch;
	bool rho_isLoaded;
	float	gen_ht_;
	TBranch *gen_ht_branch;
	bool gen_ht_isLoaded;
	int	nBJetTight_;
	TBranch *nBJetTight_branch;
	bool nBJetTight_isLoaded;
	int	nBJetMedium_;
	TBranch *nBJetMedium_branch;
	bool nBJetMedium_isLoaded;
	int	nBJetLoose_;
	TBranch *nBJetLoose_branch;
	bool nBJetLoose_isLoaded;
	int	nBJetTight_up_;
	TBranch *nBJetTight_up_branch;
	bool nBJetTight_up_isLoaded;
	int	nBJetMedium_up_;
	TBranch *nBJetMedium_up_branch;
	bool nBJetMedium_up_isLoaded;
	int	nBJetLoose_up_;
	TBranch *nBJetLoose_up_branch;
	bool nBJetLoose_up_isLoaded;
	int	nBJetTight_dn_;
	TBranch *nBJetTight_dn_branch;
	bool nBJetTight_dn_isLoaded;
	int	nBJetMedium_dn_;
	TBranch *nBJetMedium_dn_branch;
	bool nBJetMedium_dn_isLoaded;
	int	nBJetLoose_dn_;
	TBranch *nBJetLoose_dn_branch;
	bool nBJetLoose_dn_isLoaded;
	int	nJet200MuFrac50DphiMet_;
	TBranch *nJet200MuFrac50DphiMet_branch;
	bool nJet200MuFrac50DphiMet_isLoaded;
	int	nMuons10_;
	TBranch *nMuons10_branch;
	bool nMuons10_isLoaded;
	int	nBadMuons20_;
	TBranch *nBadMuons20_branch;
	bool nBadMuons20_isLoaded;
	int	nElectrons10_;
	TBranch *nElectrons10_branch;
	bool nElectrons10_isLoaded;
	int	nGammas20_;
	TBranch *nGammas20_branch;
	bool nGammas20_isLoaded;
	int	nTaus20_;
	TBranch *nTaus20_branch;
	bool nTaus20_isLoaded;
	float	met_pt_;
	TBranch *met_pt_branch;
	bool met_pt_isLoaded;
	float	met_phi_;
	TBranch *met_phi_branch;
	bool met_phi_isLoaded;
	float	met_calo_pt_;
	TBranch *met_calo_pt_branch;
	bool met_calo_pt_isLoaded;
	float	met_calo_phi_;
	TBranch *met_calo_phi_branch;
	bool met_calo_phi_isLoaded;
	float	met_miniaod_pt_;
	TBranch *met_miniaod_pt_branch;
	bool met_miniaod_pt_isLoaded;
	float	met_miniaod_phi_;
	TBranch *met_miniaod_phi_branch;
	bool met_miniaod_phi_isLoaded;
	float	met_muegclean_pt_;
	TBranch *met_muegclean_pt_branch;
	bool met_muegclean_pt_isLoaded;
	float	met_muegclean_phi_;
	TBranch *met_muegclean_phi_branch;
	bool met_muegclean_phi_isLoaded;
	float	met_rawPt_;
	TBranch *met_rawPt_branch;
	bool met_rawPt_isLoaded;
	float	met_rawPhi_;
	TBranch *met_rawPhi_branch;
	bool met_rawPhi_isLoaded;
	float	met_genPt_;
	TBranch *met_genPt_branch;
	bool met_genPt_isLoaded;
	float	met_genPhi_;
	TBranch *met_genPhi_branch;
	bool met_genPhi_isLoaded;
	float	sumet_raw_;
	TBranch *sumet_raw_branch;
	bool sumet_raw_isLoaded;
	int	Flag_ecalLaserCorrFilter_;
	TBranch *Flag_ecalLaserCorrFilter_branch;
	bool Flag_ecalLaserCorrFilter_isLoaded;
	int	Flag_hcalLaserEventFilter_;
	TBranch *Flag_hcalLaserEventFilter_branch;
	bool Flag_hcalLaserEventFilter_isLoaded;
	int	Flag_trackingFailureFilter_;
	TBranch *Flag_trackingFailureFilter_branch;
	bool Flag_trackingFailureFilter_isLoaded;
	int	Flag_CSCTightHaloFilter_;
	TBranch *Flag_CSCTightHaloFilter_branch;
	bool Flag_CSCTightHaloFilter_isLoaded;
	int	Flag_HBHENoiseFilter_;
	TBranch *Flag_HBHENoiseFilter_branch;
	bool Flag_HBHENoiseFilter_isLoaded;
	int	Flag_HBHEIsoNoiseFilter_;
	TBranch *Flag_HBHEIsoNoiseFilter_branch;
	bool Flag_HBHEIsoNoiseFilter_isLoaded;
	int	Flag_CSCTightHalo2015Filter_;
	TBranch *Flag_CSCTightHalo2015Filter_branch;
	bool Flag_CSCTightHalo2015Filter_isLoaded;
	int	Flag_EcalDeadCellTriggerPrimitiveFilter_;
	TBranch *Flag_EcalDeadCellTriggerPrimitiveFilter_branch;
	bool Flag_EcalDeadCellTriggerPrimitiveFilter_isLoaded;
	int	Flag_goodVertices_;
	TBranch *Flag_goodVertices_branch;
	bool Flag_goodVertices_isLoaded;
	int	Flag_eeBadScFilter_;
	TBranch *Flag_eeBadScFilter_branch;
	bool Flag_eeBadScFilter_isLoaded;
	int	Flag_globalTightHalo2016_;
	TBranch *Flag_globalTightHalo2016_branch;
	bool Flag_globalTightHalo2016_isLoaded;
	int	Flag_badMuonFilter_;
	TBranch *Flag_badMuonFilter_branch;
	bool Flag_badMuonFilter_isLoaded;
	int	Flag_badChargedCandidateFilter_;
	TBranch *Flag_badChargedCandidateFilter_branch;
	bool Flag_badChargedCandidateFilter_isLoaded;
	int	Flag_badMuonFilterv2_;
	TBranch *Flag_badMuonFilterv2_branch;
	bool Flag_badMuonFilterv2_isLoaded;
	int	Flag_badChargedCandidateFilterv2_;
	TBranch *Flag_badChargedCandidateFilterv2_branch;
	bool Flag_badChargedCandidateFilterv2_isLoaded;
	int	Flag_badMuons_;
	TBranch *Flag_badMuons_branch;
	bool Flag_badMuons_isLoaded;
	int	Flag_duplicateMuons_;
	TBranch *Flag_duplicateMuons_branch;
	bool Flag_duplicateMuons_isLoaded;
	int	Flag_noBadMuons_;
	TBranch *Flag_noBadMuons_branch;
	bool Flag_noBadMuons_isLoaded;
	int	HLT_singleEl_;
	TBranch *HLT_singleEl_branch;
	bool HLT_singleEl_isLoaded;
	int	HLT_singleMu_;
	TBranch *HLT_singleMu_branch;
	bool HLT_singleMu_isLoaded;
	int	HLT_singleMu_noiso_;
	TBranch *HLT_singleMu_noiso_branch;
	bool HLT_singleMu_noiso_isLoaded;
	int	HLT_DoubleEl_noiso_;
	TBranch *HLT_DoubleEl_noiso_branch;
	bool HLT_DoubleEl_noiso_isLoaded;
	int	HLT_DoubleEl_;
	TBranch *HLT_DoubleEl_branch;
	bool HLT_DoubleEl_isLoaded;
	int	HLT_DoubleEl_DZ_;
	TBranch *HLT_DoubleEl_DZ_branch;
	bool HLT_DoubleEl_DZ_isLoaded;
	int	HLT_DoubleEl_DZ_2_;
	TBranch *HLT_DoubleEl_DZ_2_branch;
	bool HLT_DoubleEl_DZ_2_isLoaded;
	int	HLT_MuEG_;
	TBranch *HLT_MuEG_branch;
	bool HLT_MuEG_isLoaded;
	int	HLT_MuEG_2_;
	TBranch *HLT_MuEG_2_branch;
	bool HLT_MuEG_2_isLoaded;
	int	HLT_MuEG_noiso_;
	TBranch *HLT_MuEG_noiso_branch;
	bool HLT_MuEG_noiso_isLoaded;
	int	HLT_MuEG_noiso_2_;
	TBranch *HLT_MuEG_noiso_2_branch;
	bool HLT_MuEG_noiso_2_isLoaded;
	int	HLT_Mu8_EG17_;
	TBranch *HLT_Mu8_EG17_branch;
	bool HLT_Mu8_EG17_isLoaded;
	int	HLT_Mu8_EG23_;
	TBranch *HLT_Mu8_EG23_branch;
	bool HLT_Mu8_EG23_isLoaded;
	int	HLT_Mu8_EG23_DZ_;
	TBranch *HLT_Mu8_EG23_DZ_branch;
	bool HLT_Mu8_EG23_DZ_isLoaded;
	int	HLT_Mu12_EG23_DZ_;
	TBranch *HLT_Mu12_EG23_DZ_branch;
	bool HLT_Mu12_EG23_DZ_isLoaded;
	int	HLT_Mu17_EG12_;
	TBranch *HLT_Mu17_EG12_branch;
	bool HLT_Mu17_EG12_isLoaded;
	int	HLT_Mu23_EG8_;
	TBranch *HLT_Mu23_EG8_branch;
	bool HLT_Mu23_EG8_isLoaded;
	int	HLT_Mu23_EG8_DZ_;
	TBranch *HLT_Mu23_EG8_DZ_branch;
	bool HLT_Mu23_EG8_DZ_isLoaded;
	int	HLT_Mu23_EG12_;
	TBranch *HLT_Mu23_EG12_branch;
	bool HLT_Mu23_EG12_isLoaded;
	int	HLT_Mu23_EG12_DZ_;
	TBranch *HLT_Mu23_EG12_DZ_branch;
	bool HLT_Mu23_EG12_DZ_isLoaded;
	int	HLT_DoubleMu_noiso_;
	TBranch *HLT_DoubleMu_noiso_branch;
	bool HLT_DoubleMu_noiso_isLoaded;
	int	HLT_DoubleMu_noiso_27_8_;
	TBranch *HLT_DoubleMu_noiso_27_8_branch;
	bool HLT_DoubleMu_noiso_27_8_isLoaded;
	int	HLT_DoubleMu_noiso_30_11_;
	TBranch *HLT_DoubleMu_noiso_30_11_branch;
	bool HLT_DoubleMu_noiso_30_11_isLoaded;
	int	HLT_DoubleMu_noiso_40_11_;
	TBranch *HLT_DoubleMu_noiso_40_11_branch;
	bool HLT_DoubleMu_noiso_40_11_isLoaded;
	int	HLT_DoubleMu_;
	TBranch *HLT_DoubleMu_branch;
	bool HLT_DoubleMu_isLoaded;
	int	HLT_DoubleMu_tk_;
	TBranch *HLT_DoubleMu_tk_branch;
	bool HLT_DoubleMu_tk_isLoaded;
	int	HLT_DoubleMu_dbltk_;
	TBranch *HLT_DoubleMu_dbltk_branch;
	bool HLT_DoubleMu_dbltk_isLoaded;
	int	HLT_DoubleMu_nonDZ_;
	TBranch *HLT_DoubleMu_nonDZ_branch;
	bool HLT_DoubleMu_nonDZ_isLoaded;
	int	HLT_DoubleMu_tk_nonDZ_;
	TBranch *HLT_DoubleMu_tk_nonDZ_branch;
	bool HLT_DoubleMu_tk_nonDZ_isLoaded;
	float	dilmass_;
	TBranch *dilmass_branch;
	bool dilmass_isLoaded;
	float	dilpt_;
	TBranch *dilpt_branch;
	bool dilpt_isLoaded;
	float	trilmass_;
	TBranch *trilmass_branch;
	bool trilmass_isLoaded;
	float	reilpt_;
	TBranch *reilpt_branch;
	bool reilpt_isLoaded;
	float	dRll_;
	TBranch *dRll_branch;
	bool dRll_isLoaded;
	float	matched_neutralemf_;
	TBranch *matched_neutralemf_branch;
	bool matched_neutralemf_isLoaded;
	float	matched_emf_;
	TBranch *matched_emf_branch;
	bool matched_emf_isLoaded;
	bool	elveto_;
	TBranch *elveto_branch;
	bool elveto_isLoaded;
	int	nlep_;
	TBranch *nlep_branch;
	bool nlep_isLoaded;
	int	nveto_leptons_;
	TBranch *nveto_leptons_branch;
	bool nveto_leptons_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *lep_p4_;
	TBranch *lep_p4_branch;
	bool lep_p4_isLoaded;
	vector<float> *lep_pt_;
	TBranch *lep_pt_branch;
	bool lep_pt_isLoaded;
	vector<float> *lep_eta_;
	TBranch *lep_eta_branch;
	bool lep_eta_isLoaded;
	vector<float> *lep_phi_;
	TBranch *lep_phi_branch;
	bool lep_phi_isLoaded;
	vector<float> *lep_mass_;
	TBranch *lep_mass_branch;
	bool lep_mass_isLoaded;
	vector<int> *lep_charge_;
	TBranch *lep_charge_branch;
	bool lep_charge_isLoaded;
	vector<int> *lep_threecharge_;
	TBranch *lep_threecharge_branch;
	bool lep_threecharge_isLoaded;
	vector<int> *lep_tightcharge_;
	TBranch *lep_tightcharge_branch;
	bool lep_tightcharge_isLoaded;
	vector<int> *lep_pdgId_;
	TBranch *lep_pdgId_branch;
	bool lep_pdgId_isLoaded;
	vector<float> *lep_dxy_;
	TBranch *lep_dxy_branch;
	bool lep_dxy_isLoaded;
	vector<float> *lep_ip3d_;
	TBranch *lep_ip3d_branch;
	bool lep_ip3d_isLoaded;
	vector<float> *lep_ip3derr_;
	TBranch *lep_ip3derr_branch;
	bool lep_ip3derr_isLoaded;
	vector<float> *lep_etaSC_;
	TBranch *lep_etaSC_branch;
	bool lep_etaSC_isLoaded;
	vector<float> *lep_dz_;
	TBranch *lep_dz_branch;
	bool lep_dz_isLoaded;
	vector<float> *lep_dzerr_;
	TBranch *lep_dzerr_branch;
	bool lep_dzerr_isLoaded;
	vector<int> *lep_vetoId_;
	TBranch *lep_vetoId_branch;
	bool lep_vetoId_isLoaded;
	vector<int> *lep_looseId_;
	TBranch *lep_looseId_branch;
	bool lep_looseId_isLoaded;
	vector<int> *lep_mediumId_;
	TBranch *lep_mediumId_branch;
	bool lep_mediumId_isLoaded;
	vector<int> *lep_tightId_;
	TBranch *lep_tightId_branch;
	bool lep_tightId_isLoaded;
	vector<float> *lep_relIso03_;
	TBranch *lep_relIso03_branch;
	bool lep_relIso03_isLoaded;
	vector<float> *lep_relIso03EA_;
	TBranch *lep_relIso03EA_branch;
	bool lep_relIso03EA_isLoaded;
	vector<float> *lep_relIso03DB_;
	TBranch *lep_relIso03DB_branch;
	bool lep_relIso03DB_isLoaded;
	vector<float> *lep_relIso04_;
	TBranch *lep_relIso04_branch;
	bool lep_relIso04_isLoaded;
	vector<float> *lep_relIso04EA_;
	TBranch *lep_relIso04EA_branch;
	bool lep_relIso04EA_isLoaded;
	vector<float> *lep_relIso04DB_;
	TBranch *lep_relIso04DB_branch;
	bool lep_relIso04DB_isLoaded;
	vector<float> *lep_ptrel_;
	TBranch *lep_ptrel_branch;
	bool lep_ptrel_isLoaded;
	vector<float> *lep_ptratio_;
	TBranch *lep_ptratio_branch;
	bool lep_ptratio_isLoaded;
	vector<int> *lep_mcMatchId_;
	TBranch *lep_mcMatchId_branch;
	bool lep_mcMatchId_isLoaded;
	vector<int> *lep_lostHits_;
	TBranch *lep_lostHits_branch;
	bool lep_lostHits_isLoaded;
	vector<int> *lep_isfromW_;
	TBranch *lep_isfromW_branch;
	bool lep_isfromW_isLoaded;
	vector<int> *lep_isfromZ_;
	TBranch *lep_isfromZ_branch;
	bool lep_isfromZ_isLoaded;
	vector<int> *lep_isfromH_;
	TBranch *lep_isfromH_branch;
	bool lep_isfromH_isLoaded;
	vector<int> *lep_isfromB_;
	TBranch *lep_isfromB_branch;
	bool lep_isfromB_isLoaded;
	vector<int> *lep_isfromC_;
	TBranch *lep_isfromC_branch;
	bool lep_isfromC_isLoaded;
	vector<int> *lep_isfromL_;
	TBranch *lep_isfromL_branch;
	bool lep_isfromL_isLoaded;
	vector<int> *lep_convVeto_;
	TBranch *lep_convVeto_branch;
	bool lep_convVeto_isLoaded;
	vector<float> *lep_MVA_;
	TBranch *lep_MVA_branch;
	bool lep_MVA_isLoaded;
	vector<float> *lep_validfraction_;
	TBranch *lep_validfraction_branch;
	bool lep_validfraction_isLoaded;
	vector<float> *lep_pterr_;
	TBranch *lep_pterr_branch;
	bool lep_pterr_isLoaded;
	vector<float> *lep_sta_pterrOpt_;
	TBranch *lep_sta_pterrOpt_branch;
	bool lep_sta_pterrOpt_isLoaded;
	vector<float> *lep_glb_pterrOpt_;
	TBranch *lep_glb_pterrOpt_branch;
	bool lep_glb_pterrOpt_isLoaded;
	vector<float> *lep_x2ondof_;
	TBranch *lep_x2ondof_branch;
	bool lep_x2ondof_isLoaded;
	vector<float> *lep_sta_x2ondof_;
	TBranch *lep_sta_x2ondof_branch;
	bool lep_sta_x2ondof_isLoaded;
	vector<float> *lep_glb_x2ondof_;
	TBranch *lep_glb_x2ondof_branch;
	bool lep_glb_x2ondof_isLoaded;
	int	nisoTracks_;
	TBranch *nisoTracks_branch;
	bool nisoTracks_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *isotr_p4_;
	TBranch *isotr_p4_branch;
	bool isotr_p4_isLoaded;
	vector<float> *isotr_relIso03_;
	TBranch *isotr_relIso03_branch;
	bool isotr_relIso03_isLoaded;
	vector<float> *isotr_relIso04_;
	TBranch *isotr_relIso04_branch;
	bool isotr_relIso04_isLoaded;
	vector<float> *isotr_ptrel_;
	TBranch *isotr_ptrel_branch;
	bool isotr_ptrel_isLoaded;
	vector<float> *isotr_ptratio_;
	TBranch *isotr_ptratio_branch;
	bool isotr_ptratio_isLoaded;
	vector<int> *isotr_charge_;
	TBranch *isotr_charge_branch;
	bool isotr_charge_isLoaded;
	vector<int> *isotr_pdgId_;
	TBranch *isotr_pdgId_branch;
	bool isotr_pdgId_isLoaded;
	vector<float> *isotr_dz_;
	TBranch *isotr_dz_branch;
	bool isotr_dz_isLoaded;
	int	nisoTrack_5gev_;
	TBranch *nisoTrack_5gev_branch;
	bool nisoTrack_5gev_isLoaded;
	int	nisoTrack_mt2_;
	TBranch *nisoTrack_mt2_branch;
	bool nisoTrack_mt2_isLoaded;
	int	nisoTrack_PFLep5_woverlaps_;
	TBranch *nisoTrack_PFLep5_woverlaps_branch;
	bool nisoTrack_PFLep5_woverlaps_isLoaded;
	int	nisoTrack_PFHad10_woverlaps_;
	TBranch *nisoTrack_PFHad10_woverlaps_branch;
	bool nisoTrack_PFHad10_woverlaps_isLoaded;
	int	ngamma_;
	TBranch *ngamma_branch;
	bool ngamma_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *gamma_p4_;
	TBranch *gamma_p4_branch;
	bool gamma_p4_isLoaded;
	vector<int> *gamma_mcMatchId_;
	TBranch *gamma_mcMatchId_branch;
	bool gamma_mcMatchId_isLoaded;
	vector<float> *gamma_genPt_;
	TBranch *gamma_genPt_branch;
	bool gamma_genPt_isLoaded;
	vector<float> *gamma_genIso_;
	TBranch *gamma_genIso_branch;
	bool gamma_genIso_isLoaded;
	vector<float> *gamma_chHadIso_;
	TBranch *gamma_chHadIso_branch;
	bool gamma_chHadIso_isLoaded;
	vector<float> *gamma_neuHadIso_;
	TBranch *gamma_neuHadIso_branch;
	bool gamma_neuHadIso_isLoaded;
	vector<float> *gamma_phIso_;
	TBranch *gamma_phIso_branch;
	bool gamma_phIso_isLoaded;
	vector<int> *gamma_idCutBased_;
	TBranch *gamma_idCutBased_branch;
	bool gamma_idCutBased_isLoaded;
	vector<float> *gamma_drMinParton_;
	TBranch *gamma_drMinParton_branch;
	bool gamma_drMinParton_isLoaded;
	int	ngenPart_;
	TBranch *ngenPart_branch;
	bool ngenPart_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *genPart_p4_;
	TBranch *genPart_p4_branch;
	bool genPart_p4_isLoaded;
	vector<float> *genPart_pt_;
	TBranch *genPart_pt_branch;
	bool genPart_pt_isLoaded;
	vector<float> *genPart_eta_;
	TBranch *genPart_eta_branch;
	bool genPart_eta_isLoaded;
	vector<float> *genPart_phi_;
	TBranch *genPart_phi_branch;
	bool genPart_phi_isLoaded;
	vector<float> *genPart_mass_;
	TBranch *genPart_mass_branch;
	bool genPart_mass_isLoaded;
	vector<int> *genPart_pdgId_;
	TBranch *genPart_pdgId_branch;
	bool genPart_pdgId_isLoaded;
	vector<int> *genPart_status_;
	TBranch *genPart_status_branch;
	bool genPart_status_isLoaded;
	vector<float> *genPart_charge_;
	TBranch *genPart_charge_branch;
	bool genPart_charge_isLoaded;
	vector<int> *genPart_motherId_;
	TBranch *genPart_motherId_branch;
	bool genPart_motherId_isLoaded;
	vector<int> *genPart_grandmaId_;
	TBranch *genPart_grandmaId_branch;
	bool genPart_grandmaId_isLoaded;
	vector<bool> *genPart_isp6status3_;
	TBranch *genPart_isp6status3_branch;
	bool genPart_isp6status3_isLoaded;
	int	njets_;
	TBranch *njets_branch;
	bool njets_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_p4_;
	TBranch *jets_p4_branch;
	bool jets_p4_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *removed_jets_p4_;
	TBranch *removed_jets_p4_branch;
	bool removed_jets_p4_isLoaded;
	vector<float> *removed_jets_csv_;
	TBranch *removed_jets_csv_branch;
	bool removed_jets_csv_isLoaded;
	vector<float> *removed_jets_deepB_;
	TBranch *removed_jets_deepB_branch;
	bool removed_jets_deepB_isLoaded;
	vector<float> *removed_jets_deepC_;
	TBranch *removed_jets_deepC_branch;
	bool removed_jets_deepC_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_medb_p4_;
	TBranch *jets_medb_p4_branch;
	bool jets_medb_p4_isLoaded;
	int	njets_up_;
	TBranch *njets_up_branch;
	bool njets_up_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_up_p4_;
	TBranch *jets_up_p4_branch;
	bool jets_up_p4_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_medb_up_p4_;
	TBranch *jets_medb_up_p4_branch;
	bool jets_medb_up_p4_isLoaded;
	vector<float> *jets_csv_;
	TBranch *jets_csv_branch;
	bool jets_csv_isLoaded;
	vector<float> *jets_up_csv_;
	TBranch *jets_up_csv_branch;
	bool jets_up_csv_isLoaded;
	vector<float> *jets_deepB_;
	TBranch *jets_deepB_branch;
	bool jets_deepB_isLoaded;
	vector<float> *jets_up_deepB_;
	TBranch *jets_up_deepB_branch;
	bool jets_up_deepB_isLoaded;
	vector<float> *jets_deepC_;
	TBranch *jets_deepC_branch;
	bool jets_deepC_isLoaded;
	vector<float> *jets_up_deepC_;
	TBranch *jets_up_deepC_branch;
	bool jets_up_deepC_isLoaded;
	int	njets_dn_;
	TBranch *njets_dn_branch;
	bool njets_dn_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_dn_p4_;
	TBranch *jets_dn_p4_branch;
	bool jets_dn_p4_isLoaded;
	vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > *jets_medb_dn_p4_;
	TBranch *jets_medb_dn_p4_branch;
	bool jets_medb_dn_p4_isLoaded;
	vector<float> *jets_dn_csv_;
	TBranch *jets_dn_csv_branch;
	bool jets_dn_csv_isLoaded;
	vector<float> *jets_dn_deepB_;
	TBranch *jets_dn_deepB_branch;
	bool jets_dn_deepB_isLoaded;
	vector<float> *jets_dn_deepC_;
	TBranch *jets_dn_deepC_branch;
	bool jets_dn_deepC_isLoaded;
	vector<float> *jets_muf_;
	TBranch *jets_muf_branch;
	bool jets_muf_isLoaded;
	vector<int> *jets_mcFlavour_;
	TBranch *jets_mcFlavour_branch;
	bool jets_mcFlavour_isLoaded;
	vector<int> *jets_mcHadronFlav_;
	TBranch *jets_mcHadronFlav_branch;
	bool jets_mcHadronFlav_isLoaded;
	float	ht_;
	TBranch *ht_branch;
	bool ht_isLoaded;
	float	ht_up_;
	TBranch *ht_up_branch;
	bool ht_up_isLoaded;
	float	ht_dn_;
	TBranch *ht_dn_branch;
	bool ht_dn_isLoaded;
	float	mt_lep1_;
	TBranch *mt_lep1_branch;
	bool mt_lep1_isLoaded;
	float	mt_min_;
	TBranch *mt_min_branch;
	bool mt_min_isLoaded;
	float	mt_max_;
	TBranch *mt_max_branch;
	bool mt_max_isLoaded;
	float	weight_btagsf_;
	TBranch *weight_btagsf_branch;
	bool weight_btagsf_isLoaded;
	float	weight_btagsf_heavy_UP_;
	TBranch *weight_btagsf_heavy_UP_branch;
	bool weight_btagsf_heavy_UP_isLoaded;
	float	weight_btagsf_light_UP_;
	TBranch *weight_btagsf_light_UP_branch;
	bool weight_btagsf_light_UP_isLoaded;
	float	weight_btagsf_heavy_DN_;
	TBranch *weight_btagsf_heavy_DN_branch;
	bool weight_btagsf_heavy_DN_isLoaded;
	float	weight_btagsf_light_DN_;
	TBranch *weight_btagsf_light_DN_branch;
	bool weight_btagsf_light_DN_isLoaded;
	float	met_T1CHS_pt_;
	TBranch *met_T1CHS_pt_branch;
	bool met_T1CHS_pt_isLoaded;
	float	met_T1CHS_phi_;
	TBranch *met_T1CHS_phi_branch;
	bool met_T1CHS_phi_isLoaded;
	float	met_T1CHS_fromCORE_pt_;
	TBranch *met_T1CHS_fromCORE_pt_branch;
	bool met_T1CHS_fromCORE_pt_isLoaded;
	float	met_T1CHS_fromCORE_phi_;
	TBranch *met_T1CHS_fromCORE_phi_branch;
	bool met_T1CHS_fromCORE_phi_isLoaded;
	float	met_T1CHS_miniAOD_CORE_pt_;
	TBranch *met_T1CHS_miniAOD_CORE_pt_branch;
	bool met_T1CHS_miniAOD_CORE_pt_isLoaded;
	float	met_T1CHS_miniAOD_CORE_phi_;
	TBranch *met_T1CHS_miniAOD_CORE_phi_branch;
	bool met_T1CHS_miniAOD_CORE_phi_isLoaded;
	float	met_T1CHS_miniAOD_CORE_up_pt_;
	TBranch *met_T1CHS_miniAOD_CORE_up_pt_branch;
	bool met_T1CHS_miniAOD_CORE_up_pt_isLoaded;
	float	met_T1CHS_miniAOD_CORE_up_phi_;
	TBranch *met_T1CHS_miniAOD_CORE_up_phi_branch;
	bool met_T1CHS_miniAOD_CORE_up_phi_isLoaded;
	float	met_T1CHS_miniAOD_CORE_dn_pt_;
	TBranch *met_T1CHS_miniAOD_CORE_dn_pt_branch;
	bool met_T1CHS_miniAOD_CORE_dn_pt_isLoaded;
	float	met_T1CHS_miniAOD_CORE_dn_phi_;
	TBranch *met_T1CHS_miniAOD_CORE_dn_phi_branch;
	bool met_T1CHS_miniAOD_CORE_dn_phi_isLoaded;
	int	hyp_type_;
	TBranch *hyp_type_branch;
	bool hyp_type_isLoaded;
	int	evt_type_;
	TBranch *evt_type_branch;
	bool evt_type_isLoaded;
	float	isrboost_;
	TBranch *isrboost_branch;
	bool isrboost_isLoaded;
	int	isr_njets_;
	TBranch *isr_njets_branch;
	bool isr_njets_isLoaded;
	float	isr_weight_;
	TBranch *isr_weight_branch;
	bool isr_weight_isLoaded;
	float	isr_unc_;
	TBranch *isr_unc_branch;
	bool isr_unc_isLoaded;
	vector<float> *weightsf_lepid_;
	TBranch *weightsf_lepid_branch;
	bool weightsf_lepid_isLoaded;
	vector<float> *weightsf_lepiso_;
	TBranch *weightsf_lepiso_branch;
	bool weightsf_lepiso_isLoaded;
	vector<float> *weightsf_lepip_;
	TBranch *weightsf_lepip_branch;
	bool weightsf_lepip_isLoaded;
	vector<float> *weightsf_lepreco_;
	TBranch *weightsf_lepreco_branch;
	bool weightsf_lepreco_isLoaded;
	vector<float> *weightsf_lepconv_;
	TBranch *weightsf_lepconv_branch;
	bool weightsf_lepconv_isLoaded;
	vector<float> *weightsf_lepid_FS_;
	TBranch *weightsf_lepid_FS_branch;
	bool weightsf_lepid_FS_isLoaded;
	vector<float> *weightsf_lepiso_FS_;
	TBranch *weightsf_lepiso_FS_branch;
	bool weightsf_lepiso_FS_isLoaded;
	vector<float> *weightsf_lepip_FS_;
	TBranch *weightsf_lepip_FS_branch;
	bool weightsf_lepip_FS_isLoaded;
public: 
void Init(TTree *tree);
void GetEntry(unsigned int idx); 
void LoadAllBranches(); 
	const int &run();
	const int &lumi();
	const unsigned long long &evt();
	const int &isData();
	const bool &	evt_passgoodrunlist();
	const float &evt_scale1fb();
	const float &evt_xsec();
	const float &evt_kfactor();
	const float &evt_filter();
	const int &evt_nEvts();
	const vector<TString> &evt_dataset();
	const float &puWeight();
	const int &nVert();
	const int &nTrueInt();
	const float &rho();
	const float &gen_ht();
	const int &nBJetTight();
	const int &nBJetMedium();
	const int &nBJetLoose();
	const int &nBJetTight_up();
	const int &nBJetMedium_up();
	const int &nBJetLoose_up();
	const int &nBJetTight_dn();
	const int &nBJetMedium_dn();
	const int &nBJetLoose_dn();
	const int &nJet200MuFrac50DphiMet();
	const int &nMuons10();
	const int &nBadMuons20();
	const int &nElectrons10();
	const int &nGammas20();
	const int &nTaus20();
	const float &met_pt();
	const float &met_phi();
	const float &met_calo_pt();
	const float &met_calo_phi();
	const float &met_miniaod_pt();
	const float &met_miniaod_phi();
	const float &met_muegclean_pt();
	const float &met_muegclean_phi();
	const float &met_rawPt();
	const float &met_rawPhi();
	const float &met_genPt();
	const float &met_genPhi();
	const float &sumet_raw();
	const int &Flag_ecalLaserCorrFilter();
	const int &Flag_hcalLaserEventFilter();
	const int &Flag_trackingFailureFilter();
	const int &Flag_CSCTightHaloFilter();
	const int &Flag_HBHENoiseFilter();
	const int &Flag_HBHEIsoNoiseFilter();
	const int &Flag_CSCTightHalo2015Filter();
	const int &Flag_EcalDeadCellTriggerPrimitiveFilter();
	const int &Flag_goodVertices();
	const int &Flag_eeBadScFilter();
	const int &Flag_globalTightHalo2016();
	const int &Flag_badMuonFilter();
	const int &Flag_badChargedCandidateFilter();
	const int &Flag_badMuonFilterv2();
	const int &Flag_badChargedCandidateFilterv2();
	const int &Flag_badMuons();
	const int &Flag_duplicateMuons();
	const int &Flag_noBadMuons();
	const int &HLT_singleEl();
	const int &HLT_singleMu();
	const int &HLT_singleMu_noiso();
	const int &HLT_DoubleEl_noiso();
	const int &HLT_DoubleEl();
	const int &HLT_DoubleEl_DZ();
	const int &HLT_DoubleEl_DZ_2();
	const int &HLT_MuEG();
	const int &HLT_MuEG_2();
	const int &HLT_MuEG_noiso();
	const int &HLT_MuEG_noiso_2();
	const int &HLT_Mu8_EG17();
	const int &HLT_Mu8_EG23();
	const int &HLT_Mu8_EG23_DZ();
	const int &HLT_Mu12_EG23_DZ();
	const int &HLT_Mu17_EG12();
	const int &HLT_Mu23_EG8();
	const int &HLT_Mu23_EG8_DZ();
	const int &HLT_Mu23_EG12();
	const int &HLT_Mu23_EG12_DZ();
	const int &HLT_DoubleMu_noiso();
	const int &HLT_DoubleMu_noiso_27_8();
	const int &HLT_DoubleMu_noiso_30_11();
	const int &HLT_DoubleMu_noiso_40_11();
	const int &HLT_DoubleMu();
	const int &HLT_DoubleMu_tk();
	const int &HLT_DoubleMu_dbltk();
	const int &HLT_DoubleMu_nonDZ();
	const int &HLT_DoubleMu_tk_nonDZ();
	const float &dilmass();
	const float &dilpt();
	const float &trilmass();
	const float &reilpt();
	const float &dRll();
	const float &matched_neutralemf();
	const float &matched_emf();
	const bool &	elveto();
	const int &nlep();
	const int &nveto_leptons();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &lep_p4();
	const vector<float> &lep_pt();
	const vector<float> &lep_eta();
	const vector<float> &lep_phi();
	const vector<float> &lep_mass();
	const vector<int> &lep_charge();
	const vector<int> &lep_threecharge();
	const vector<int> &lep_tightcharge();
	const vector<int> &lep_pdgId();
	const vector<float> &lep_dxy();
	const vector<float> &lep_ip3d();
	const vector<float> &lep_ip3derr();
	const vector<float> &lep_etaSC();
	const vector<float> &lep_dz();
	const vector<float> &lep_dzerr();
	const vector<int> &lep_vetoId();
	const vector<int> &lep_looseId();
	const vector<int> &lep_mediumId();
	const vector<int> &lep_tightId();
	const vector<float> &lep_relIso03();
	const vector<float> &lep_relIso03EA();
	const vector<float> &lep_relIso03DB();
	const vector<float> &lep_relIso04();
	const vector<float> &lep_relIso04EA();
	const vector<float> &lep_relIso04DB();
	const vector<float> &lep_ptrel();
	const vector<float> &lep_ptratio();
	const vector<int> &lep_mcMatchId();
	const vector<int> &lep_lostHits();
	const vector<int> &lep_isfromW();
	const vector<int> &lep_isfromZ();
	const vector<int> &lep_isfromH();
	const vector<int> &lep_isfromB();
	const vector<int> &lep_isfromC();
	const vector<int> &lep_isfromL();
	const vector<int> &lep_convVeto();
	const vector<float> &lep_MVA();
	const vector<float> &lep_validfraction();
	const vector<float> &lep_pterr();
	const vector<float> &lep_sta_pterrOpt();
	const vector<float> &lep_glb_pterrOpt();
	const vector<float> &lep_x2ondof();
	const vector<float> &lep_sta_x2ondof();
	const vector<float> &lep_glb_x2ondof();
	const int &nisoTracks();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &isotr_p4();
	const vector<float> &isotr_relIso03();
	const vector<float> &isotr_relIso04();
	const vector<float> &isotr_ptrel();
	const vector<float> &isotr_ptratio();
	const vector<int> &isotr_charge();
	const vector<int> &isotr_pdgId();
	const vector<float> &isotr_dz();
	const int &nisoTrack_5gev();
	const int &nisoTrack_mt2();
	const int &nisoTrack_PFLep5_woverlaps();
	const int &nisoTrack_PFHad10_woverlaps();
	const int &ngamma();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gamma_p4();
	const vector<int> &gamma_mcMatchId();
	const vector<float> &gamma_genPt();
	const vector<float> &gamma_genIso();
	const vector<float> &gamma_chHadIso();
	const vector<float> &gamma_neuHadIso();
	const vector<float> &gamma_phIso();
	const vector<int> &gamma_idCutBased();
	const vector<float> &gamma_drMinParton();
	const int &ngenPart();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genPart_p4();
	const vector<float> &genPart_pt();
	const vector<float> &genPart_eta();
	const vector<float> &genPart_phi();
	const vector<float> &genPart_mass();
	const vector<int> &genPart_pdgId();
	const vector<int> &genPart_status();
	const vector<float> &genPart_charge();
	const vector<int> &genPart_motherId();
	const vector<int> &genPart_grandmaId();
	const vector<bool> &genPart_isp6status3();
	const int &njets();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_p4();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &removed_jets_p4();
	const vector<float> &removed_jets_csv();
	const vector<float> &removed_jets_deepB();
	const vector<float> &removed_jets_deepC();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_p4();
	const int &njets_up();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_up_p4();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_up_p4();
	const vector<float> &jets_csv();
	const vector<float> &jets_up_csv();
	const vector<float> &jets_deepB();
	const vector<float> &jets_up_deepB();
	const vector<float> &jets_deepC();
	const vector<float> &jets_up_deepC();
	const int &njets_dn();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_dn_p4();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_dn_p4();
	const vector<float> &jets_dn_csv();
	const vector<float> &jets_dn_deepB();
	const vector<float> &jets_dn_deepC();
	const vector<float> &jets_muf();
	const vector<int> &jets_mcFlavour();
	const vector<int> &jets_mcHadronFlav();
	const float &ht();
	const float &ht_up();
	const float &ht_dn();
	const float &mt_lep1();
	const float &mt_min();
	const float &mt_max();
	const float &weight_btagsf();
	const float &weight_btagsf_heavy_UP();
	const float &weight_btagsf_light_UP();
	const float &weight_btagsf_heavy_DN();
	const float &weight_btagsf_light_DN();
	const float &met_T1CHS_pt();
	const float &met_T1CHS_phi();
	const float &met_T1CHS_fromCORE_pt();
	const float &met_T1CHS_fromCORE_phi();
	const float &met_T1CHS_miniAOD_CORE_pt();
	const float &met_T1CHS_miniAOD_CORE_phi();
	const float &met_T1CHS_miniAOD_CORE_up_pt();
	const float &met_T1CHS_miniAOD_CORE_up_phi();
	const float &met_T1CHS_miniAOD_CORE_dn_pt();
	const float &met_T1CHS_miniAOD_CORE_dn_phi();
	const int &hyp_type();
	const int &evt_type();
	const float &isrboost();
	const int &isr_njets();
	const float &isr_weight();
	const float &isr_unc();
	const vector<float> &weightsf_lepid();
	const vector<float> &weightsf_lepiso();
	const vector<float> &weightsf_lepip();
	const vector<float> &weightsf_lepreco();
	const vector<float> &weightsf_lepconv();
	const vector<float> &weightsf_lepid_FS();
	const vector<float> &weightsf_lepiso_FS();
	const vector<float> &weightsf_lepip_FS();

  static void progress( int nEventsTotal, int nEventsChain );
};

#ifndef __CINT__
extern triboson_v1 cms3;
#endif

namespace triboson_v1_np {
	const int &run();
	const int &lumi();
	const unsigned long long &evt();
	const int &isData();
	const bool &evt_passgoodrunlist();
	const float &evt_scale1fb();
	const float &evt_xsec();
	const float &evt_kfactor();
	const float &evt_filter();
	const int &evt_nEvts();
	const vector<TString> &evt_dataset();
	const float &puWeight();
	const int &nVert();
	const int &nTrueInt();
	const float &rho();
	const float &gen_ht();
	const int &nBJetTight();
	const int &nBJetMedium();
	const int &nBJetLoose();
	const int &nBJetTight_up();
	const int &nBJetMedium_up();
	const int &nBJetLoose_up();
	const int &nBJetTight_dn();
	const int &nBJetMedium_dn();
	const int &nBJetLoose_dn();
	const int &nJet200MuFrac50DphiMet();
	const int &nMuons10();
	const int &nBadMuons20();
	const int &nElectrons10();
	const int &nGammas20();
	const int &nTaus20();
	const float &met_pt();
	const float &met_phi();
	const float &met_calo_pt();
	const float &met_calo_phi();
	const float &met_miniaod_pt();
	const float &met_miniaod_phi();
	const float &met_muegclean_pt();
	const float &met_muegclean_phi();
	const float &met_rawPt();
	const float &met_rawPhi();
	const float &met_genPt();
	const float &met_genPhi();
	const float &sumet_raw();
	const int &Flag_ecalLaserCorrFilter();
	const int &Flag_hcalLaserEventFilter();
	const int &Flag_trackingFailureFilter();
	const int &Flag_CSCTightHaloFilter();
	const int &Flag_HBHENoiseFilter();
	const int &Flag_HBHEIsoNoiseFilter();
	const int &Flag_CSCTightHalo2015Filter();
	const int &Flag_EcalDeadCellTriggerPrimitiveFilter();
	const int &Flag_goodVertices();
	const int &Flag_eeBadScFilter();
	const int &Flag_globalTightHalo2016();
	const int &Flag_badMuonFilter();
	const int &Flag_badChargedCandidateFilter();
	const int &Flag_badMuonFilterv2();
	const int &Flag_badChargedCandidateFilterv2();
	const int &Flag_badMuons();
	const int &Flag_duplicateMuons();
	const int &Flag_noBadMuons();
	const int &HLT_singleEl();
	const int &HLT_singleMu();
	const int &HLT_singleMu_noiso();
	const int &HLT_DoubleEl_noiso();
	const int &HLT_DoubleEl();
	const int &HLT_DoubleEl_DZ();
	const int &HLT_DoubleEl_DZ_2();
	const int &HLT_MuEG();
	const int &HLT_MuEG_2();
	const int &HLT_MuEG_noiso();
	const int &HLT_MuEG_noiso_2();
	const int &HLT_Mu8_EG17();
	const int &HLT_Mu8_EG23();
	const int &HLT_Mu8_EG23_DZ();
	const int &HLT_Mu12_EG23_DZ();
	const int &HLT_Mu17_EG12();
	const int &HLT_Mu23_EG8();
	const int &HLT_Mu23_EG8_DZ();
	const int &HLT_Mu23_EG12();
	const int &HLT_Mu23_EG12_DZ();
	const int &HLT_DoubleMu_noiso();
	const int &HLT_DoubleMu_noiso_27_8();
	const int &HLT_DoubleMu_noiso_30_11();
	const int &HLT_DoubleMu_noiso_40_11();
	const int &HLT_DoubleMu();
	const int &HLT_DoubleMu_tk();
	const int &HLT_DoubleMu_dbltk();
	const int &HLT_DoubleMu_nonDZ();
	const int &HLT_DoubleMu_tk_nonDZ();
	const float &dilmass();
	const float &dilpt();
	const float &trilmass();
	const float &reilpt();
	const float &dRll();
	const float &matched_neutralemf();
	const float &matched_emf();
	const bool &elveto();
	const int &nlep();
	const int &nveto_leptons();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &lep_p4();
	const vector<float> &lep_pt();
	const vector<float> &lep_eta();
	const vector<float> &lep_phi();
	const vector<float> &lep_mass();
	const vector<int> &lep_charge();
	const vector<int> &lep_threecharge();
	const vector<int> &lep_tightcharge();
	const vector<int> &lep_pdgId();
	const vector<float> &lep_dxy();
	const vector<float> &lep_ip3d();
	const vector<float> &lep_ip3derr();
	const vector<float> &lep_etaSC();
	const vector<float> &lep_dz();
	const vector<float> &lep_dzerr();
	const vector<int> &lep_vetoId();
	const vector<int> &lep_looseId();
	const vector<int> &lep_mediumId();
	const vector<int> &lep_tightId();
	const vector<float> &lep_relIso03();
	const vector<float> &lep_relIso03EA();
	const vector<float> &lep_relIso03DB();
	const vector<float> &lep_relIso04();
	const vector<float> &lep_relIso04EA();
	const vector<float> &lep_relIso04DB();
	const vector<float> &lep_ptrel();
	const vector<float> &lep_ptratio();
	const vector<int> &lep_mcMatchId();
	const vector<int> &lep_lostHits();
	const vector<int> &lep_isfromW();
	const vector<int> &lep_isfromZ();
	const vector<int> &lep_isfromH();
	const vector<int> &lep_isfromB();
	const vector<int> &lep_isfromC();
	const vector<int> &lep_isfromL();
	const vector<int> &lep_convVeto();
	const vector<float> &lep_MVA();
	const vector<float> &lep_validfraction();
	const vector<float> &lep_pterr();
	const vector<float> &lep_sta_pterrOpt();
	const vector<float> &lep_glb_pterrOpt();
	const vector<float> &lep_x2ondof();
	const vector<float> &lep_sta_x2ondof();
	const vector<float> &lep_glb_x2ondof();
	const int &nisoTracks();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &isotr_p4();
	const vector<float> &isotr_relIso03();
	const vector<float> &isotr_relIso04();
	const vector<float> &isotr_ptrel();
	const vector<float> &isotr_ptratio();
	const vector<int> &isotr_charge();
	const vector<int> &isotr_pdgId();
	const vector<float> &isotr_dz();
	const int &nisoTrack_5gev();
	const int &nisoTrack_mt2();
	const int &nisoTrack_PFLep5_woverlaps();
	const int &nisoTrack_PFHad10_woverlaps();
	const int &ngamma();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gamma_p4();
	const vector<int> &gamma_mcMatchId();
	const vector<float> &gamma_genPt();
	const vector<float> &gamma_genIso();
	const vector<float> &gamma_chHadIso();
	const vector<float> &gamma_neuHadIso();
	const vector<float> &gamma_phIso();
	const vector<int> &gamma_idCutBased();
	const vector<float> &gamma_drMinParton();
	const int &ngenPart();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genPart_p4();
	const vector<float> &genPart_pt();
	const vector<float> &genPart_eta();
	const vector<float> &genPart_phi();
	const vector<float> &genPart_mass();
	const vector<int> &genPart_pdgId();
	const vector<int> &genPart_status();
	const vector<float> &genPart_charge();
	const vector<int> &genPart_motherId();
	const vector<int> &genPart_grandmaId();
	const vector<bool> &genPart_isp6status3();
	const int &njets();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_p4();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &removed_jets_p4();
	const vector<float> &removed_jets_csv();
	const vector<float> &removed_jets_deepB();
	const vector<float> &removed_jets_deepC();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_p4();
	const int &njets_up();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_up_p4();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_up_p4();
	const vector<float> &jets_csv();
	const vector<float> &jets_up_csv();
	const vector<float> &jets_deepB();
	const vector<float> &jets_up_deepB();
	const vector<float> &jets_deepC();
	const vector<float> &jets_up_deepC();
	const int &njets_dn();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_dn_p4();
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_dn_p4();
	const vector<float> &jets_dn_csv();
	const vector<float> &jets_dn_deepB();
	const vector<float> &jets_dn_deepC();
	const vector<float> &jets_muf();
	const vector<int> &jets_mcFlavour();
	const vector<int> &jets_mcHadronFlav();
	const float &ht();
	const float &ht_up();
	const float &ht_dn();
	const float &mt_lep1();
	const float &mt_min();
	const float &mt_max();
	const float &weight_btagsf();
	const float &weight_btagsf_heavy_UP();
	const float &weight_btagsf_light_UP();
	const float &weight_btagsf_heavy_DN();
	const float &weight_btagsf_light_DN();
	const float &met_T1CHS_pt();
	const float &met_T1CHS_phi();
	const float &met_T1CHS_fromCORE_pt();
	const float &met_T1CHS_fromCORE_phi();
	const float &met_T1CHS_miniAOD_CORE_pt();
	const float &met_T1CHS_miniAOD_CORE_phi();
	const float &met_T1CHS_miniAOD_CORE_up_pt();
	const float &met_T1CHS_miniAOD_CORE_up_phi();
	const float &met_T1CHS_miniAOD_CORE_dn_pt();
	const float &met_T1CHS_miniAOD_CORE_dn_phi();
	const int &hyp_type();
	const int &evt_type();
	const float &isrboost();
	const int &isr_njets();
	const float &isr_weight();
	const float &isr_unc();
	const vector<float> &weightsf_lepid();
	const vector<float> &weightsf_lepiso();
	const vector<float> &weightsf_lepip();
	const vector<float> &weightsf_lepreco();
	const vector<float> &weightsf_lepconv();
	const vector<float> &weightsf_lepid_FS();
	const vector<float> &weightsf_lepiso_FS();
	const vector<float> &weightsf_lepip_FS();
}
#endif
